### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Kami147** [TheGrimSilence/Minecraft-Forge-1.12.2#6]
didn't this used to have the 1.12.2 src on it lol? what happened?

**Comment by henryleberre** [comment]
Yes it did! I know this is an old issue, but for any future readers, some of the forks at least contain the source code.

**Comment by TheGrimSilence** [comment]
Late reply, due to copyright I was forced to pull the code, but you can simply clone and run the deobf task to generate the source code again
